
# .github/workflows/cd-status-tracker.yml
name: Call CD Status Tracker Action

on:
  workflow_dispatch:

jobs:
  call-cd-status-tracker:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Call the custom action from cd-status-tracker
      - name: Run CD Status Tracker
        uses: shundor/cd-status-tracker@main
        with:
          environment: production
          version: ${{ github.sha }}
